config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  get "/sync", to: "home#do_sync", as: :sync
  get "/async", to: "home#do_async", as: :async
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/generic_task.rb
class GenericTask
  def do_something
    Rails.logger.warn("STARTING generic task.")
    # ... code to do stuff here
    Rails.logger.warn("FINISHED generic task.")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def do_sync
    task = GenericTask.new
    task.do_something

    redirect_to action: :index
  end

  def do_async
    LoggingJob.perform_async

    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Hello Sidekiq</h1>

<%= link_to("Do Sync Job", sync_url) %>
<p />
<%= link_to("Do Async Job", async_url) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SidekiqLogging</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>